name: Test

on: [pull_request]

jobs:
  cypress-test:
     runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Headless Chrome
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
          headless: true
          record: false